# Project: LMS
# Makefile created by Embarcadero Dev-C++ 6.3

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = Book.o Librarian.o Library.o Student.o User.o main.o ../Users/scs/Desktop/LibraryManagementSystem/Database.o
LINKOBJ  = Book.o Librarian.o Library.o Student.o User.o main.o ../Users/scs/Desktop/LibraryManagementSystem/Database.o
LIBS     = -L"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/lib" -L"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/lib" -L"C:/Program Files/MySQL/MySQL Server 8.0/lib" -static-libgcc -lmysql
INCS     = -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/include" -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include"
CXXINCS  = -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/include" -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++" -I"C:/Program Files/MySQL/MySQL Server 8.0/lib"
BIN      = LMS.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
DEL      = C:\Program Files (x86)\Embarcadero\Dev-Cpp\DevCpp.exe INTERNAL_DEL

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${DEL} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

Book.o: Book.cpp
	$(CPP) -c Book.cpp -o Book.o $(CXXFLAGS)

Librarian.o: Librarian.cpp
	$(CPP) -c Librarian.cpp -o Librarian.o $(CXXFLAGS)

Library.o: Library.cpp
	$(CPP) -c Library.cpp -o Library.o $(CXXFLAGS)

Student.o: Student.cpp
	$(CPP) -c Student.cpp -o Student.o $(CXXFLAGS)

User.o: User.cpp
	$(CPP) -c User.cpp -o User.o $(CXXFLAGS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

../Users/scs/Desktop/LibraryManagementSystem/Database.o: ../Users/scs/Desktop/LibraryManagementSystem/Database.cpp
	$(CPP) -c ../Users/scs/Desktop/LibraryManagementSystem/Database.cpp -o ../Users/scs/Desktop/LibraryManagementSystem/Database.o $(CXXFLAGS)
